#markdown: redcarpet# Site settings
title: Progra a la Tica
email: ssanchez77@gmail.com
description: >
  Notas y tips sobre programación, en español.
  Este es una simple libreta de notas, en donde publicaré apuntes
  acerca de conceptos y resolución de problemas de mi día a día.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ssanchez77.github.io" # the base hostname & protocol for your site
twitter_username: ssanchez77
github_username:  ssanchez77

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

markdown_ext: markdown,mkdown,mkdn,mkd,md
excerpt_separator: <!--more-->

#markdown: redcarpet
#redcarpet:
#  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]

# Includes
include: [.htaccess]

# Other settings
timezone: America/Costa_Rica
