# Site settings
title: Cuaderno de Apuntes
email: ssanchez77[arroba]gmail.com
description: >
  Notas y tips sobre programación, en español.
  Este es un simple cuaderno de notas, en donde publicaré apuntes
  acerca de conceptos y resolución de problemas de mi día a día.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://simon-sanchez.com" # the base hostname & protocol for your site
twitter_username: ssanchez77
github_username:  ssanchez77

# Build settings
markdown: kramdown

# Includes
include: .htaccess

# Other settings
timezone: America/Costa_Rica
